name: "Run Pytest"
on: 
  push:
  pull_request:

jobs:
  pg:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        ports:
        - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: user
          PGDATA: /var/lib/postgresql/data/pgdata
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  test:
    needs: pg
    runs-on: ubuntu-latestS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Укажите вашу версию Python (3.8, 3.9, 3.10, 3.11)

      # Шаг 3: Установка зависимостей (если у вас есть requirements.txt)
      - name: Install dependencies
        run: |
          cd Lab1
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          alembic upgrade head
      # Шаг 4: Запуск ваших тестов
      - name: Run tests with pytest
        run: |
          python -m pytest tests/test_user.py -v