name: "Run Pytest"
on: 
  push:
  pull_request:

jobs:    
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        ports:
        - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: user
          PGDATA: /var/lib/postgresql/data/pgdata
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      # Шаг 3: Установка зависимостей 
      - name: Install dependencies
        run: |
          cd Lab1
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install setuptools
          pip install -e .
          alembic upgrade head
      # Шаг 4: Запуск ваших тестов
      - name: Run tests with pytest
        run: |
          cd Lab1
          python -m pytest tests/test_user.py -v